const EMOJI_MAP = [
  { k: ['onion','pyaz'],                        e: '🧅' },
  { k: ['tomato','tamatar'],                    e: '🍅' },
  { k: ['potato','aloo'],                       e: '🥔' },
  { k: ['garlic','lahsun'],                     e: '🧄' },
  { k: ['ginger','adrak'],                      e: '🫚' },
  { k: ['carrot','gajar'],                      e: '🥕' },
  { k: ['capsicum','shimla','bell pepper'],      e: '🫑' },
  { k: ['cauliflower','gobi'],                  e: '🥦' },
  { k: ['spinach','palak'],                     e: '🥬' },
  { k: ['brinjal','baingan','eggplant'],        e: '🍆' },
  { k: ['bhindi','okra','ladyfinger'],          e: '🫛' },
  { k: ['cucumber','kakdi'],                    e: '🥒' },
  { k: ['lemon','nimbu'],                       e: '🍋' },
  { k: ['chilli','chili','mirch'],              e: '🌶️' },
  { k: ['peas','matar'],                        e: '🫘' },
  { k: ['corn','maize','makka'],                e: '🌽' },
  { k: ['mushroom'],                            e: '🍄' },
  { k: ['cabbage','patta'],                     e: '🥬' },
  { k: ['pumpkin','kaddu'],                     e: '🎃' },
  { k: ['apple','seb'],                         e: '🍎' },
  { k: ['banana','kela'],                       e: '🍌' },
  { k: ['mango','aam'],                         e: '🥭' },
  { k: ['orange','santra'],                     e: '🍊' },
  { k: ['grape','angur'],                       e: '🍇' },
  { k: ['watermelon','tarbuj'],                 e: '🍉' },
  { k: ['coconut','nariyal'],                   e: '🥥' },
  { k: ['milk','doodh'],                        e: '🥛' },
  { k: ['butter','makhan'],                     e: '🧈' },
  { k: ['cheese','paneer'],                     e: '🧀' },
  { k: ['curd','dahi','yogurt'],                e: '🫙' },
  { k: ['ghee'],                                e: '🫙' },
  { k: ['atta','flour','wheat'],                e: '🌾' },
  { k: ['rice','chawal','basmati'],             e: '🍚' },
  { k: ['dal','daal','lentil'],                 e: '🫘' },
  { k: ['oats','quaker'],                       e: '🥣' },
  { k: ['cornflake','cereal','muesli'],         e: '🥣' },
  { k: ['maggi','noodle','pasta','yippee'],     e: '🍜' },
  { k: ['soup'],                                e: '🍲' },
  { k: ['salt','namak'],                        e: '🧂' },
  { k: ['sugar','chini','shakkar'],             e: '🍬' },
  { k: ['oil','tel','saffola','sunflower'],     e: '🫙' },
  { k: ['masala','spice'],                      e: '🌶️' },
  { k: ['ketchup','sauce'],                     e: '🍅' },
  { k: ['pickle','achar'],                      e: '🫙' },
  { k: ['chips','lays','crisps'],               e: '🍟' },
  { k: ['mixture','namkeen','bhujia','haldiram'], e: '🥜' },
  { k: ['popcorn'],                             e: '🍿' },
  { k: ['peanut','mungfali'],                   e: '🥜' },
  { k: ['cashew','kaju'],                       e: '🌰' },
  { k: ['almond','badam'],                      e: '🌰' },
  { k: ['biscuit','parle','good day','marie','bourbon','oreo','sunfeast','britannia'], e: '🍪' },
  { k: ['bread','roti','pav','bun'],            e: '🍞' },
  { k: ['cake','pastry','muffin'],              e: '🎂' },
  { k: ['tea','chai','tata tea','lipton'],      e: '🍵' },
  { k: ['coffee','bru','nescafe'],              e: '☕' },
  { k: ['juice','frooti','maaza','slice'],      e: '🧃' },
  { k: ['water','kinley','bisleri'],            e: '💧' },
  { k: ['soda','pepsi','cola','sprite','limca','fanta','cold drink'], e: '🥤' },
  { k: ['chocolate','dairy milk','kitkat','5 star','cadbury'], e: '🍫' },
  { k: ['candy','toffee','eclairs'],            e: '🍬' },
  { k: ['ice cream','kulfi'],                   e: '🍦' },
  { k: ['egg','anda'],                          e: '🥚' },
  { k: ['chicken','murgi'],                     e: '🍗' },
  { k: ['fish','machli'],                       e: '🐟' },
  { k: ['surf','ariel','tide','rin','detergent','washing powder'], e: '🫧' },
  { k: ['vim','pril','dishwash'],               e: '🧽' },
  { k: ['phenyl','floor cleaner','harpic','lizol','colin'], e: '🧴' },
  { k: ['broom','jhadu'],                       e: '🧹' },
  { k: ['soap','lifebuoy','lux','dove'],        e: '🧼' },
  { k: ['handwash','hand wash','dettol','savlon'], e: '🫧' },
  { k: ['shampoo','pantene','sunsilk'],         e: '🧴' },
  { k: ['toothpaste','colgate','pepsodent'],    e: '🪥' },
  { k: ['toothbrush'],                          e: '🪥' },
  { k: ['lotion','vaseline','moisturizer'],     e: '💆' },
  { k: ['hair oil','parachute','vatika'],       e: '💆' },
  { k: ['deodorant','deo','axe','rexona'],      e: '🌸' },
  { k: ['razor','shaving','gillette'],          e: '🪒' },
  { k: ['baby','diaper','pampers','huggies'],   e: '👶' },
  { k: ['medicine','tablet','syrup','capsule','dolo','crocin'], e: '💊' },
  { k: ['match','matchbox','lighter'],          e: '🔥' },
  { k: ['candle','agarbatti','incense'],        e: '🕯️' },
  { k: ['amul'],                                e: '🥛' },
  { k: ['tata'],                                e: '🏭' },
];

export function getProductEmoji(name = '', unit = '') {
  const lower = name.toLowerCase();
  for (const { k, e } of EMOJI_MAP) {
    if (k.some((kw) => lower.includes(kw))) return e;
  }
  if (unit === 'kg') return '⚖️';
  return '📦';
}

